source 'https://cdn.cocoapods.org/'

workspace 'RaLog.xcworkspace'

platform :ios, '10.0'

use_frameworks!

#use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :preserve_pod_file_structure => true,
         :generate_multiple_pod_projects => true
#         :incremental_installation => true

target 'RaLog' do
  
  project 'RaLog/RaLog.xcodeproj'
  
  
  
end
